✅ Iteration 13
Jourloy/go-metrics-collector pull request #13
Opened 2023-11-12 18:31 UTC by Jourloy

2023-11-14 21:11 UTC, vovean requested changes

2023-11-14 21:11 UTC, vovean commented on .env.server.template
> +# STORE_INTERVAL=300
тут было бы классной практикой не в комментариях указывать, что эта штука в секундах, а сделать поле, куда это будет анмаршалиться типом type.Duration. И тогда ты можешь в енв переменных писать красивые значения, например, 300s, 200ms, 100ns, 2m и т д

2023-11-14 21:11 UTC, vovean commented on Dockerfile
> +FROM golang:1.21
лучшей практикой в мире гошки является использование multistage building, чтобы в первом стейдже ты билдил, делаешь на основе (FROM) большого жирного образа где есть все нужное, а итоговый стейдж, который и будет пушиться в реджистри и сохраняться в виде имаджа делаешь на основе alpine / scratch, который очень легкий и туда копируешь только скомпиленый бинарь из первого стейджа

Вот тут простейший пример: https://docs.docker.com/build/building/multi-stage/

2023-11-14 21:11 UTC, vovean commented on docker-compose.yml
> +        command: go run ./cmd/server
запуск через go run будет тебе каждый раз вызывать компиляцию. Не круто, потому что для больших приложений компиляция может занимать минуты. Лучше в имадже докера хранить уже готовый бинарь

2023-11-14 21:11 UTC, vovean commented on docker-compose.yml
> +            - postgres
наверное, агент еще и от сервера зависит, иначе будет слать свои данные в молоко

2023-11-14 21:11 UTC, vovean commented on internal/agent/collector/collector.go
> +				}
вкусовщина, но switch-case тут выглядел бы симпатично + с ним тебе придется всего 1 раз разименовывать переменную

2023-11-14 21:11 UTC, vovean commented on internal/agent/collector/collector.go
> +			return status, err
выглядит как прям вот дубликат функции выше. Может сделать функцию, которая будет принимать параметр и запускать вот эту твою функцию, используя параметр как замыкание? Тогда уберешь кол-во дублирования кода

2023-11-14 21:11 UTC, vovean commented on internal/agent/collector/collector.go
> +	b, _ := json.Marshal(metrics)
ай ай ай, ошибку стоит обработать, тут ничего сложного

2023-11-14 21:11 UTC, vovean commented on internal/agent/collector/collector.go
> +	return &res.StatusCode, nil
а зачем ты тут возвращаешь именно указатель? Просто значение не покатит?

2023-11-14 21:11 UTC, vovean commented on internal/agent/collector/collector.go
> +	for errorsCount < 3 {
такое лучше либо в константу вынести, а еще лучше - в параметр функции

А вообще лучше не изобретать велосипед и заиспользовать готовое решение, например, https://github.com/avast/retry-go - мы такое в Ситидрайве в проде используем и она прям удобная

2023-11-14 21:11 UTC, vovean commented on internal/agent/collector/collector.go
> +		timer := (1 + (errorsCount * 2))
классно, что сделал увеличивающийся backoff, это хорошая тема

2023-11-14 21:11 UTC, vovean commented on internal/agent/collector/collector.go
> +func (c *Collector) retryIfError(f func() (*int, error)) error {
на хабре у яндекса есть прям суууупер крутая статья про ретраи, почитай как время будет: https://habr.com/ru/companies/yandex/articles/762678/

2023-11-14 21:11 UTC, vovean commented on internal/server/app/app.go
> +		ctx.String(http.StatusBadRequest, err.Error())
залогировать?

2023-11-14 21:11 UTC, vovean commented on internal/server/app/app.go
> +		ctx.String(http.StatusBadRequest, err.Error())
и в остальных местах, где клиенту улетает ошибка стоит логировать. Иначе у тебя однажды случится баг, клиенту начнет улетать супер много ошибок, а ты не поймешь, откуда ошибки клиенту летят то вообще

2023-11-14 21:11 UTC, vovean commented on internal/server/app/app.go
> +	defer ctx.Request.Body.Close()
неа, не надо

не имеет смысл делать это на стороне сервера, только на стороне клиента при запросе

ты это делаешь, чтобы на стороне клиента поскорее (или хотя бы вообще не забыть) отдать ОС коннект, чтобы он дальше переиспользовался бы. Но на стороне сервера тебе в этот коннект еще ответ писать, так что гошка его явно никуда не отдаст и вот это действие закрытия тела, по сути, бесполезно

2023-11-14 21:11 UTC, vovean commented on internal/server/app/app.go
> +		updated = Metric{
можно сразу это вернуть, а не тащить до самого низа функции

тогда ветку else if ты сможешь убрать и оставшийся код написать без лишней вложенности. А даже если так не делать, то хотя бы кода читать будет меньше, чтоб понять, а где же update используется дальше

2023-11-14 21:11 UTC, vovean commented on internal/server/app/app.go
> +		return Metric{}, errType
вот это можно сделать в самом начале, и можем делать early return

2023-11-14 21:11 UTC, vovean commented on internal/server/app/app.go
> +		return
сделать проверку перед основной бизнес логикой, а не после

2023-11-14 21:11 UTC, vovean commented on internal/server/app/app.go
> +		return
и во всех остальных местах

2023-11-14 21:11 UTC, vovean commented on internal/server/server.go
> +	Host = flag.String(`a`, `localhost:8080`, `Host of the server`)
блин, все таки, никак я не пойму, а в чем сакральная идея использовать бэк-тики, что аж все остальные типы кавычек выпиливать

2023-11-14 21:11 UTC, vovean commented on internal/server/server.go
> +			responseSize := c.Writer.Size()
а почему size логируется только для get? Размер ответа на POST и другие запросы не интересует?

2023-11-14 21:11 UTC, vovean commented on internal/server/storage/repository/postgres/postgres.go
> +func (r *PostgresStorage) StartTickers() {}
вот отличный пример нарушения буквы I из SOLID - Interface Segregation. Метод тебе реально не нужен, но пришлось реализовать, чтобы удовлетворить интерфейс. Стоит подумать о разделении интерфейса репозитория на более мелкие интерфейсы. Кажется, метод про тикеры - что-то специфичное для in-memory или file хранилища, но не для идеи репозитория в общем. Стоит вынести такое из общего интерфейса

2023-11-14 21:11 UTC, vovean commented on internal/server/storage/repository/postgres/postgres.go
> +	gauge := make(map[string]float64)
можно в этих мапах сразу выделить память на кол-во элементов равное длине слайса

2023-11-14 21:11 UTC, vovean commented on internal/server/storage/repository/postgres/postgres.go
> +		return r.db.Get(&counterModel, `SELECT * FROM counter WHERE name = $1`, name)
select * вообще не хорошая тема, потому что очень уж много тут может поломаться, ты не контролируешь процесс размапливания. Не критично, но лучше сканить явно в конкретные поля

2023-11-14 21:11 UTC, vovean commented on internal/server/storage/repository/postgres/postgres.go
> +		if err := retryIfError(func() error {
а если это была вообще ошибка коннекта к базе из-за того, что сеть умерла? Может имеет смысл идти делать инсерт только в каком-то ограниченном количестве кейсов?

2023-11-14 21:11 UTC, vovean commented on internal/server/storage/repository/postgres/postgres.go
> +// UpdateGaugeMetric updates the gauge metric with the given name and value in the MemStorage.
тут коммент устарел

2023-11-14 21:11 UTC, vovean commented on internal/server/storage/repository/repository.go
> +func CreateRepository() storage.Storage {
принимай интерфейсы, **возвращай структуры**

2023-11-14 21:11 UTC, vovean commented on internal/server/storage/storage.go
> +	StartTickers()
наличие метода конкретной реализации в общем интерфейсе - очень плохо

2023-11-15 04:05 UTC, Jourloy commented on internal/server/server.go
> +	Host = flag.String(`a`, `localhost:8080`, `Host of the server`)
Перфекционизм, мне проще смотреть на такой код
```go
import "time"
a := `1
2
3`
flag.String(`a`, `...`, `...`)
```
Чем на такой
```go
import "time"
a := `1
2
3`
flag.String("r", "...", "...")
```
Хочется, чтобы был один стиль на всем проекте. Импорты - `""`, все остальное - бэк-тики

2023-11-15 04:28 UTC, Jourloy commented on internal/agent/collector/collector.go
> +	return &res.StatusCode, nil
Чтобы выше была возможность вернуть `nil`. Или так лучше не делать и возвращать просто 0, к примеру?

2023-11-15 05:16 UTC, Jourloy commented on internal/server/app/app.go
> +		return Metric{}, errType
Обновил код в этом месте. Стоит ли теперь делать в начале проверку на тип и делать return или оставить два if'а?

2023-11-15 05:28 UTC, Jourloy commented on internal/server/server.go
> +			responseSize := c.Writer.Size()
Не задумывался даже, честно говоря)

2023-11-15 05:30 UTC, Jourloy commented on internal/server/storage/repository/postgres/postgres.go
> +		if err := retryIfError(func() error {
Что в старой функции (на момент ревью), что в новой (после ревью), в этой функции проверка на класс ошибки или если ошибка равна Class 08, то ретраим, иначе нет. Поэтому, ретраи будут только если нет возможности достучаться до БД

2023-11-15 06:42 UTC, Jourloy commented on Dockerfile
> +FROM golang:1.21
Сделал build, но multi-stage не реализовал, так как в таком случае Docker не хочет никак запускать, может проблема в том, что я на винде

2023-11-21 18:50 UTC, vovean approved these changes

2023-11-26 18:58 UTC, merged