Iteration 5
Jourloy/go-metrics-collector pull request #5
Opened 2023-10-04 13:35 UTC by Jourloy

2023-10-08 14:48 UTC, vovean requested changes

2023-10-08 14:48 UTC, vovean commented on cmd/agent/README.md
> +$ go test ./cmd/agent/...
хм, так в этом пакете нет тестов же... что будет протестировано этой командой?

2023-10-08 14:48 UTC, vovean commented on internal/agent/collector/collector.go
> +	done    chan bool
можно использовать chan struct{}, чтобы объекты канала совсем не занимали памяти

2023-10-08 14:48 UTC, vovean commented on internal/agent/collector/collector.go
> +	}
подумай, как можно избежать лишней вложенности кода и обойтись без этого else

2023-10-08 14:48 UTC, vovean commented on internal/agent/collector/collector.go
> +	fmt.Println(`Collector's tickers started`)
может стоит использовать какую-нибудь полноценную библиотеку для логирования? Например, zap или zerolog или logrus

2023-10-08 14:48 UTC, vovean commented on internal/agent/collector/collector.go
> +func (c *Collector) StopTickers() bool {
зачем здесь возвращаемое значение?

2023-10-08 14:48 UTC, vovean commented on internal/agent/collector/collector.go
> +	hostENV, exist := os.LookupEnv(`ADDRESS`)
не очень "говорящее" название переменной окружения. Адрес чего? Яндекса? Пентагона?

2023-10-08 14:48 UTC, vovean commented on internal/agent/collector/collector.go
> +	hostENV, exist := os.LookupEnv(`ADDRESS`)
к тому же, получается, ты будешь при каждом вызове этого метода вытаскивать одну и ту же env переменную. Не очень эффективно.

Может стоит вычитать ее 1 раз и сохранить? А потом использовать сохраненное значение?

Это касается и остальных переменных окружения

2023-10-08 14:48 UTC, vovean commented on internal/agent/collector/collector_test.go
> +			assert.True(t, state)
как ты думаешь, не будет ли в этом тесте гонки?

2023-10-08 14:48 UTC, vovean commented on internal/agent/collector/collector_test.go
> +			name: `Positive #1`,
есть ли другие тест-кейсы?

2023-10-08 14:48 UTC, vovean commented on internal/server/app/app.go
> +	merged := make(map[string]any)
может сразу выделить необходимый объем памяти? Сумма размеров всех мап с метриками

2023-10-08 14:48 UTC, vovean commented on internal/server/collector/collector.go
> +	}
а если это не gauge и не counter? Может стоит вернуть ошибку в таком случае

2023-10-08 14:48 UTC, vovean commented on internal/server/collector/collector.go
> +	// Prepare for .env
не очень понимаю этот комментарий

2023-10-08 14:48 UTC, vovean commented on internal/server/collector/collector.go
> +		fmt.Println(errNotFound.Error(), `on`, urlString)
on? странное сообщение об ошибке

2023-10-08 14:48 UTC, vovean commented on internal/server/collector/collector.go
> +		u[i] = strings.Replace(u[i], `%20`, ``, -1)
может сделать полноценный url decode? Потому что кроме %20 существует еще немало символов, которые могут быть закодированы через "процент-последовательности"

https://www.urldecoder.io/golang/

2023-10-08 14:48 UTC, vovean commented on internal/server/collector/collector.go
> +	if param == `` {
зачем использовать бэк-тики? Можно простые двойны кавычки

2023-10-08 14:48 UTC, vovean commented on internal/server/collector/collector_test.go
> +	}
можно еще добавить тест на gauge

2023-10-08 14:48 UTC, vovean commented on internal/server/collector/collector_test.go
> +				assert.Equal(t, tt.wantErrMessage, err.Error())
тут можно сразу return

2023-10-08 14:48 UTC, vovean commented on internal/server/collector/collector.go
> +	if param == `` {
позже обратил внимание, что тут везде используются бэк-тики. В общем то это не ошибка, но и не целевое применение этой фичи голанга. Бэк-тики были сделаны, чтобы писать строки, содержащие escape-последовательности, которые пришлось бы обрабатывать особым образом в строках с использованием двойных кавычек. В этом проекте я таких кейсов не вижу, так что я бы ожидал использование двойных кавычек

2023-10-08 14:48 UTC, vovean commented on internal/server/handlers/collector_handler.go
> +	r.POST(metricEndpoint+`/:type`+`/:name`+`/:value`, collectorHandler.ServeHTTP)
может сразу написать путь одной целой строкой? К чему этот конструктор, сборка строки?

2023-10-08 14:48 UTC, vovean commented on internal/server/server.go
> +	}
может сначала определить значение переменной-адреса сервера, потом отдельно запускать сервер? Уменьшим ветвление, вложенность и дублирование кода

2023-10-08 14:48 UTC, vovean commented on internal/server/storage/repository/repository.go
> +	}
`r.counter[name] += value` даст такой же результат как эти 5 строк кода

2023-10-09 10:57 UTC, Jourloy commented on internal/server/collector/collector.go
> +		fmt.Println(errNotFound.Error(), `on`, urlString)
Суть была в том, чтобы увидеть на каком url была ошибка

2023-10-09 11:12 UTC, Jourloy commented on internal/server/collector/collector.go
> +	}
Чуть выше идет как раз проверка на типы

2023-10-09 11:13 UTC, Jourloy commented on internal/agent/collector/collector_test.go
> +			assert.True(t, state)
Думаю нет, так как тикеры запускаются сразу и нам не важно, пройдет ли один тик или нет. Или я не прав?

2023-10-09 11:25 UTC, Jourloy commented on internal/server/collector/collector.go
> +	if param == `` {
Насколько это критично? Просто сложилась определенная привычка использования бэк-тиков, так как это универсальный символ, который разом решает все проблемы)

Но если нужно, то могу все заменить

2023-10-09 11:29 UTC, Jourloy commented on internal/agent/collector/collector.go
> +	hostENV, exist := os.LookupEnv(`ADDRESS`)
Заменил код, но имя самой env переменной не могу, так как это же ТЗ яндекса. Заменил название самой переменной

2023-10-09 11:34 UTC, Jourloy commented
То, что я поправил - зарезолвил

Но насколько я понял, у всех разная политика резолва ревью. Я что сделал - закрыл, чтобы не мешалось. Что не закрыл - оставил коммент

Если неправильно сделал, прошу поправить меня)

2023-10-10 21:27 UTC, vovean approved these changes
все круто, отличная работа! Оставил комменты рекомендательного характера

2023-10-10 21:27 UTC, vovean commented on internal/agent/collector/collector.go
> +	PollInterval   = flag.Int("p", 2, "Poll Interval")
https://pkg.go.dev/flag#Duration

2023-10-10 21:27 UTC, vovean commented on internal/agent/collector/collector.go
> +			c.sendMetrics()
а не должно ли тут быть вычитывание канала done?

2023-10-10 21:27 UTC, vovean commented on internal/agent/collector/collector.go
> +	zap.L().Debug(`Metrics sended`)
sent

2023-10-10 21:27 UTC, vovean commented on internal/server/collector/collector.go
> +// Finally, it sets the response status to OK and returns the response.
комменты шикарны, правда

если писал сам, то респект. Если генерил нейронкой, то респект х10))

2023-10-10 21:27 UTC, vovean commented on internal/server/collector/collector.go
> +	if param == `` {
не критично) просто большая часть разработчиков использует обычные кавычки и, если над проектом работает несколько человек, то у вас начнется смешение стилей кавычек

2023-10-10 21:42 UTC, Jourloy commented on internal/server/collector/collector.go
> +// Finally, it sets the response status to OK and returns the response.
Да, генерирую нейронкой, потом проверяю на соответствие

Вообще от таких больших комментариев пытаюсь избавляться, так как на мой взгляд, они сильно растянуты, этот, видимо, пропустил)

Но теперь задумаюсь, может и не стоит)

2023-10-20 21:02 UTC, merged